### ISSUE TITLE
How to get raw image file like `rust.raw`?

### ISSUE THREAD

**Issue by SKTT1Ryze** [jamwaffles/ssd1331#10]
I have used the `rust.raw` in the `example` dir and following codes to render rust logo on my waveshare p-paper:  
```Rust
let data = include_bytes!("../rust.raw");
let raw: ImageRaw<BinaryColor> = ImageRaw::new(data, 64, 64);
    
let image = Image::new(&raw, Point::new(10, 10));
image.draw(&mut display).unwrap();
```
That's cool ! Thanks so much !  
But when I want to render some other logos or images with their raw files, it's a problem that how can I get raw file of the image I want to render?  
I have tried some online png2raw tools to generate raw files from png files, but I don't know the width and the height of them.  
So, how can I get raw files of specified images?  
Thanks for your answer.

**Comment by SKTT1Ryze** [comment]
close this issue.

**Comment by jamwaffles** [comment]
Apologies for not responding. Hopefully by self-closing this issue you found a solution :). If not, there's an Imagemagick command in `examples/image.rs` which should provide a starting point:

```bash
convert rust.png -depth 1 gray:rust.raw
```

I admit this is not very easy to find!

**Comment by SKTT1Ryze** [comment]
Thanks very much!
