### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by David-OConnor** [jamwaffles/ssd1331#9]
Hi. Do you know what could cause this to crash on the `.flush()` or `.draw` steps? After reset and init, the screen will turn on and show static noise.

I'm using an STM32F3 dev board. I've confirmed that the display and cables work on a Raspberry Pi using Python. My code is very similar to the examples. I'm pulling the `CS` pin low. Thank you. 

Of note, I got your SSD1306 module on I2C working without trouble, but I suppose the different interface doesn't help troubleshoot here.

**Comment by jamwaffles** [comment]
I'm not sure what the issue might be. Is it a crash or just a hang waiting for SPI perhaps? I don't know how much RAM the specific chip you're using has, but it's worth checking to see if the framebuffer fits into it.

Is your test code small enough to post here completely? Even better, a link to a repo to look at would be great.

**Comment by David-OConnor** [comment]
It started working, and I'm not sure what I did wrong earlier. Sorry about the trouble. It may have been related to attempting to store the struct with buffer statically.

**Comment by jamwaffles** [comment]
No worries! I've had issues with the SSD1331 in the past where it locks up and a good long power cycle seems to fix it. YMMV :shrug: :grin:
